version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_quiosconext
    restart: always
    environment:
      POSTGRES_DB: quiosconext
      POSTGRES_USER: quiosco_user
      POSTGRES_PASSWORD: quiosco_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
